services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    env_file:
      - ./backend/.env

  backend:
    build:
      context: ./backend
    volumes:
      - backend_db_data:/app/db
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./backend/.env
    command: ["uvicorn", "app.main:app", "--host", "backend", "--port", "8001", "--workers", "2"]

  celery:
    build:
      context: ./backend
    volumes:
      - backend_db_data:/app/db
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - ./backend/.env
    command: ["celery", "-A", "app.audio_tasks", "worker", "--loglevel=info", "--concurrency=1"]

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env.local

  stt:
    build:
      context: ./tool
    volumes:
      - ./tool:/app
    ports:
      - "8002:8002"
    env_file:
      - ./tool/.env

volumes:
  backend_db_data:
