version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    volumes:
      - backend_db_data:/app/db
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--workers", "4"]

  celery:
    build:
      context: ./backend
    volumes:
      - backend_db_data:/app/db
    depends_on:
      - redis
      - backend
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: ["celery", "-A", "app.audio_tasks", "worker", "--loglevel=info", "--concurrency=1"]

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  stt:
    build:
      context: ./tool
    volumes:
      - ./tool:/app
    ports:
      - "8002:8002"

volumes:
  backend_db_data:
